services:

  backend:
    build: .
    container_name: game-backend
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: games
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - .:/app

  redis:
    image: redis:7
    container_name: game-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: game-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: games
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d games"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: